template(name="rewrite_identity" type="list") {
    property(name="timestamp")
    constant(value=" ")
    property(name="hostname")
    constant(value=" ")
    property(name="syslogtag" position.from="21")
    constant(value=" ")
    property(name="msg")
    constant(value="\n")
}

if ( $syslogtag startswith "[sufficit][identity]" ) then {
    action( type     = "omfile"
            file     = "/var/log/sufficit/identity.log"
            template = "rewrite_identity"
    )
    stop
}
