namespace Sufficit.Identity.Core.Entities;

/// <summary>
/// A durable server-side browser session for the ASP.NET Core Identity
/// application cookie. One row per active SSO session at the STS itself,
/// keyed by the opaque OIDC <c>sid</c> claim (the same value
/// <c>OidcSessionClaimsPrincipalFactory</c> mints and projects into ID
/// tokens / logout_tokens).
/// </summary>
/// <remarks>
/// <para>
/// Backs the <c>ITicketStore</c> wired to
/// <see cref="Microsoft.AspNetCore.Identity.IdentityConstants.ApplicationScheme"/>
/// via <c>CookieAuthenticationOptions.SessionStore</c>. The browser receives
/// only the opaque <see cref="SessionId"/> as its session cookie value; the
/// full <c>AuthenticationTicket</c> (principal + claims + properties) lives
/// in <see cref="ProtectedTicket"/>, DataProtection-protected and serialized
/// exactly as <c>PasskeyAuthenticationTicketStore</c> does for the 2FA cookie.
/// </para>
/// <para>
/// This is the store of *browser* sessions, orthogonal to the OpenIddict
/// token/authorization records that represent *issued OAuth credentials*.
/// Revoking a row here (<c>RemoveAsync(sid)</c>) immediately invalidates that
/// single browser session; revoking all rows for a subject kills every device.
/// The global per-user revocation (security-stamp bump) continues to work
/// alongside via <c>SecurityStampValidator</c>.
/// </para>
/// </remarks>
public sealed class OidcUserSession
{
    /// <summary>Database primary key (identity).</summary>
    public long Id { get; set; }

    /// <summary>
    /// The OIDC <c>sid</c> / the <c>ITicketStore</c> key. Unique per session.
    /// Generated by <c>OidcSessionClaimsPrincipalFactory</c> (32 random bytes,
    /// base64url) and reused on <c>RefreshSignInAsync</c> so account edits do
    /// not look like a new OP session.
    /// </summary>
    public string SessionId { get; set; } = string.Empty;

    /// <summary>The authenticated user's subject (<c>AspNetUsers.Id</c>).</summary>
    public string Subject { get; set; } = string.Empty;

    /// <summary>
    /// Best-effort capture of the signing-in device's IP, for the future
    /// "devices" UX. Nullable; absent in tests and machine-to-machine paths.
    /// </summary>
    public string? RemoteIpAddress { get; set; }

    /// <summary>
    /// Best-effort capture of the signing-in browser's User-Agent, for the
    /// future "devices" UX. Nullable.
    /// </summary>
    public string? UserAgent { get; set; }

    /// <summary>When the session was first created (UTC).</summary>
    public DateTime CreatedAtUtc { get; set; }

    /// <summary>
    /// Last time the session was observed active (UTC). Refreshed on each
    /// <c>RetrieveAsync</c> (i.e. every cookie-authenticated request).
    /// </summary>
    public DateTime LastActivityUtc { get; set; }

    /// <summary>
    /// Optional absolute expiration (UTC), derived from the ticket's
    /// <c>ExpiresUtc</c>. Null = no absolute expiry (sliding only).
    /// </summary>
    public DateTime? ExpiresUtc { get; set; }

    /// <summary>
    /// The DataProtection-protected, <c>TicketSerializer</c>-serialized
    /// <c>AuthenticationTicket</c>. Opaque; never inspected outside the store.
    /// </summary>
    public byte[] ProtectedTicket { get; set; } = Array.Empty<byte>();
}
