using OpenIddict.Abstractions;
using Sufficit.Identity.Application.Security;

namespace Sufficit.Identity.STS;

/// <summary>
/// Adapter-specific helper for dynamic registration. The actual protocol
/// invariants are implemented by the shared application validator so DCR,
/// management and provisioning cannot drift apart.
/// </summary>
internal static class DynamicClientDefinitionValidation
{
    public static ClientDefinitionValidationResult Validate(
        IClientDefinitionValidator validator,
        Controllers.DcrRequest request,
        DcrOptions options,
        string clientType,
        bool hasClientSecret)
    {
        if (!string.IsNullOrWhiteSpace(request.ClientId)
            && !options.AllowCallerSuppliedClientIds)
        {
            return new ClientDefinitionValidationResult([
                new(
                    "invalid_client_metadata",
                    "clientId",
                    "client_id is generated by the authorization server."),
            ]);
        }

        if (!string.IsNullOrWhiteSpace(request.ClientSecret)
            && !options.AllowCallerSuppliedSecrets)
        {
            return new ClientDefinitionValidationResult([
                new(
                    "invalid_client_metadata",
                    "clientSecret",
                    "client_secret is generated by the authorization server."),
            ]);
        }

        var authenticationMethod = string.IsNullOrWhiteSpace(
            request.TokenEndpointAuthMethod)
            ? "none"
            : request.TokenEndpointAuthMethod;
        if (authenticationMethod is not
            ("none" or "client_secret_basic" or "client_secret_post"))
        {
            return new ClientDefinitionValidationResult([
                new(
                    "invalid_client_metadata",
                    "tokenEndpointAuthMethod",
                    "token_endpoint_auth_method is not supported."),
            ]);
        }

        var grants = request.GrantTypes ?? [];
        var scopes = request.Scopes ?? [];
        return validator.Validate(new ClientDefinitionRequest(
            ClientDefinitionSource.DynamicRegistration,
            request.ClientId,
            clientType,
            grants,
            scopes,
            request.RedirectUris,
            RequirePkce: grants.Contains(
                OpenIddictConstants.GrantTypes.AuthorizationCode,
                StringComparer.Ordinal),
            hasClientSecret,
            AllowedGrantTypes: options.AllowedGrantTypes.ToHashSet(
                StringComparer.Ordinal),
            AllowedScopes: options.AllowedScopes.ToHashSet(
                StringComparer.Ordinal)));
    }
}
