// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sufficit.Identity.Core.Data;

#nullable disable

namespace Sufficit.Identity.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905172658_AddVaultSecretTypes")]
    partial class AddVaultSecretTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("longtext")
                        .HasColumnName("friendlyname");

                    b.Property<string>("Xml")
                        .HasColumnType("longtext")
                        .HasColumnName("xml");

                    b.HasKey("Id");

                    b.ToTable("dataprotectionkeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext")
                        .HasColumnName("claimtype");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext")
                        .HasColumnName("claimvalue");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("roleid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("roleclaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext")
                        .HasColumnName("claimtype");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext")
                        .HasColumnName("claimvalue");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("userclaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("loginprovider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("providerkey");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext")
                        .HasColumnName("providerdisplayname");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("userid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("userlogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("varbinary(1024)")
                        .HasColumnName("credentialid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("userid");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_userpasskeys_userid");

                    b.ToTable("userpasskeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("userid");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("roleid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("userroles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("userid");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("loginprovider");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("longtext")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("usertokens", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("application_type");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("longtext")
                        .HasColumnName("client_secret");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("client_type");

                    b.Property<string>("ConcurrencyToken")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("consent_type");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext")
                        .HasColumnName("display_name");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("longtext")
                        .HasColumnName("display_names");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("longtext")
                        .HasColumnName("json_web_key_set");

                    b.Property<string>("Permissions")
                        .HasColumnType("longtext")
                        .HasColumnName("permissions");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("longtext")
                        .HasColumnName("post_logout_redirect_uris");

                    b.Property<string>("Properties")
                        .HasColumnType("longtext")
                        .HasColumnName("properties");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("longtext")
                        .HasColumnName("redirect_uris");

                    b.Property<string>("Requirements")
                        .HasColumnType("longtext")
                        .HasColumnName("requirements");

                    b.Property<string>("Settings")
                        .HasColumnType("longtext")
                        .HasColumnName("settings");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasDatabaseName("AK_OpenIddictApplications_ClientId");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("application_id");

                    b.Property<string>("ConcurrencyToken")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_date");

                    b.Property<string>("Properties")
                        .HasColumnType("longtext")
                        .HasColumnName("properties");

                    b.Property<string>("Scopes")
                        .HasColumnType("longtext")
                        .HasColumnName("scopes");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type")
                        .HasDatabaseName("IX_OpenIddictAuthorizations_ApplicationId_Status_Subject_Type");

                    b.ToTable("authorizations", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyToken")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Descriptions")
                        .HasColumnType("longtext")
                        .HasColumnName("descriptions");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext")
                        .HasColumnName("display_name");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("longtext")
                        .HasColumnName("display_names");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Properties")
                        .HasColumnType("longtext")
                        .HasColumnName("properties");

                    b.Property<string>("Resources")
                        .HasColumnType("longtext")
                        .HasColumnName("resources");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("AK_OpenIddictScopes_Name");

                    b.ToTable("scopes", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("application_id");

                    b.Property<string>("AuthorizationId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("authorization_id");

                    b.Property<string>("ConcurrencyToken")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_date");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiration_date");

                    b.Property<string>("Payload")
                        .HasColumnType("longtext")
                        .HasColumnName("payload");

                    b.Property<string>("Properties")
                        .HasColumnType("longtext")
                        .HasColumnName("properties");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("redemption_date");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("reference_id")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId")
                        .HasDatabaseName("IX_OpenIddictTokens_AuthorizationId");

                    b.HasIndex("ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("AK_OpenIddictTokens_ReferenceId");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type")
                        .HasDatabaseName("IX_OpenIddictTokens_ApplicationId_Status_Subject_Type");

                    b.ToTable("tokens", (string)null);
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext")
                        .HasColumnName("concurrencystamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalizedname");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("accessfailedcount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext")
                        .HasColumnName("concurrencystamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdatutc")
                        .HasDefaultValueSql("(UTC_TIMESTAMP(6))");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("emailconfirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("lockoutenabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lockoutend");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalizedemail");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalizedusername");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext")
                        .HasColumnName("passwordhash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("phonenumber");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("phonenumberconfirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext")
                        .HasColumnName("securitystamp");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("(UTC_TIMESTAMP())");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("Timestamp"));

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("twofactorenabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_users_createdatutc");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.BrandingTheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrlTemplate")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("avatarurltemplate");

                    b.Property<string>("BackgroundImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("backgroundimageurl");

                    b.Property<string>("BrandColor")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("brandcolor");

                    b.Property<string>("BrandHoverColor")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("brandhovercolor");

                    b.Property<string>("BrandName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("brandname");

                    b.Property<string>("BrandSoftColor")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("brandsoftcolor");

                    b.Property<string>("BrandSubtitle")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("brandsubtitle");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<string>("FaviconUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("faviconurl");

                    b.Property<string>("HeaderIconUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("headericonurl");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isactive");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("logourl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("ThemeColor")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("themecolor");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updatedat");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_brandingthemes_isactive");

                    b.ToTable("brandingthemes", (string)null);
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.CibaPendingState", b =>
                {
                    b.Property<string>("AuthReqId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("authreqid")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("ApprovedSubject")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("approvedsubject");

                    b.Property<string>("BindingMessage")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)")
                        .HasColumnName("bindingmessage");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("clientid");

                    b.Property<string>("ConsumptionId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("consumptionid")
                        .UseCollation("utf8mb4_bin");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdatutc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiresatutc");

                    b.Property<DateTime>("LastPollAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastpollatutc");

                    b.Property<string>("ScopesJson")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("scopesjson");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("state");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("subject");

                    b.HasKey("AuthReqId");

                    b.HasIndex("ConsumptionId")
                        .IsUnique()
                        .HasDatabaseName("AK_cibapendingstates_consumptionid");

                    b.HasIndex("State", "ExpiresAtUtc")
                        .HasDatabaseName("IX_cibapendingstates_state_expiresatutc");

                    b.ToTable("cibapendingstates", (string)null);
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.DpopReplayEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("key")
                        .UseCollation("utf8mb4_bin");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiresatutc");

                    b.HasKey("Key");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_dpopreplayentries_expiresatutc");

                    b.ToTable("dpopreplayentries", (string)null);
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.IdentityApplicationUsageEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("clientid");

                    b.Property<string>("EndpointType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("endpointtype");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("eventtype");

                    b.Property<string>("GrantType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("granttype");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("occurredatutc");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("outcome");

                    b.Property<string>("SubjectHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("subjecthash");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("IX_identityusage_occurredatutc");

                    b.HasIndex("ClientId", "OccurredAtUtc")
                        .HasDatabaseName("IX_identityusage_clientid_occurredatutc");

                    b.HasIndex("EventType", "OccurredAtUtc")
                        .HasDatabaseName("IX_identityusage_eventtype_occurredatutc");

                    b.ToTable("identityapplicationusageevents", (string)null);
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.IdentityMetricsConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AuthorizationScheme")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("authorizationscheme");

                    b.Property<int>("BatchSize")
                        .HasColumnType("int")
                        .HasColumnName("batchsize");

                    b.Property<string>("Database")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("database");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("endpoint");

                    b.Property<bool>("ExportEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("exportenabled");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("provider");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("int")
                        .HasColumnName("retentiondays");

                    b.Property<string>("SecretCiphertext")
                        .HasColumnType("longtext")
                        .HasColumnName("secretciphertext");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("int")
                        .HasColumnName("timeoutseconds");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updatedatutc");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("identitymetricsconfiguration", (string)null);
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.ManagementAuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AuthenticationMethods")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("authenticationmethods");

                    b.Property<string>("AuthorizationOutcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("authorizationoutcome");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("capability");

                    b.Property<string>("ContextId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contextid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correlationid");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("occurredatutc");

                    b.Property<string>("OperationOutcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("operationoutcome");

                    b.Property<string>("OperatorDisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("operatordisplayname");

                    b.Property<string>("OperatorSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("operatorsubject");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("reasoncode");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("resourceid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("resourcetype");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("IX_managementauditevents_occurredatutc");

                    b.HasIndex("ResourceType", "ResourceId")
                        .HasDatabaseName("IX_managementauditevents_resource");

                    b.ToTable("managementauditevents", (string)null);
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.ManagementClientDraftRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .UseCollation("ascii_bin");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdatutc");

                    b.Property<string>("CreatedClientId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("createdclientid");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("currentstep");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiresatutc");

                    b.Property<string>("OwnerSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ownersubject");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("profile");

                    b.Property<string>("ProtectedPayload")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("protectedpayload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updatedatutc");

                    b.Property<string>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_managementclientdrafts_expiresatutc");

                    b.HasIndex("OwnerSubject", "Status", "UpdatedAtUtc")
                        .HasDatabaseName("IX_managementclientdrafts_owner_status_updated");

                    b.ToTable("managementclientdrafts", (string)null);
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.OAuthClientCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("clientid")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("concurrencytoken");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdatutc");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiresatutc");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("label");

                    b.Property<DateTime?>("NotBeforeUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("notbeforeutc");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("revocationreason");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revokedatutc");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("secrethash");

                    b.Property<string>("SecretHint")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("secrethint");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_oauthclientcredentials_expiresatutc");

                    b.HasIndex("ClientId", "Kind", "RevokedAtUtc", "ExpiresAtUtc")
                        .HasDatabaseName("IX_oauthclientcredentials_client_kind_status");

                    b.ToTable("oauthclientcredentials", (string)null);
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.OidcUserSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdatutc");

                    b.Property<DateTime?>("ExpiresUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiresutc");

                    b.Property<DateTime>("LastActivityUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastactivityutc");

                    b.Property<byte[]>("ProtectedTicket")
                        .IsRequired()
                        .HasColumnType("longblob")
                        .HasColumnName("protectedticket");

                    b.Property<string>("RemoteIpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("remoteipaddress");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sessionid")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("subject");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("useragent");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresUtc")
                        .HasDatabaseName("IX_oidcusersessions_expiresutc");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("AK_oidcusersessions_sessionid");

                    b.HasIndex("Subject")
                        .HasDatabaseName("IX_oidcusersessions_subject");

                    b.ToTable("oidcusersessions", (string)null);
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.ProtocolStateEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("key")
                        .UseCollation("utf8mb4_bin");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiresatutc");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("longblob")
                        .HasColumnName("payload");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("purpose");

                    b.HasKey("Key");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_protocolstateentries_expiresatutc");

                    b.HasIndex("Purpose")
                        .HasDatabaseName("IX_protocolstateentries_purpose");

                    b.ToTable("protocolstateentries", (string)null);
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.ScimGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("concurrencystamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdatutc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("displayname");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("externalid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updatedatutc");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("IX_scimgroups_displayname");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("IX_scimgroups_externalid");

                    b.ToTable("scimgroups", (string)null);
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.ScimGroupGroupMember", b =>
                {
                    b.Property<string>("GroupId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("groupid");

                    b.Property<string>("MemberGroupId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("membergroupid");

                    b.HasKey("GroupId", "MemberGroupId");

                    b.HasIndex("MemberGroupId")
                        .HasDatabaseName("IX_scimgroupgroupmembers_membergroupid");

                    b.ToTable("scimgroupgroupmembers", (string)null);
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.ScimGroupUserMember", b =>
                {
                    b.Property<string>("GroupId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("groupid");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("userid");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_scimgroupusermembers_userid");

                    b.ToTable("scimgroupusermembers", (string)null);
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.ScimUserProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("userid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdatutc");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("displayname");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("externalid");

                    b.Property<string>("FamilyName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("familyname");

                    b.Property<string>("FormattedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("formattedname");

                    b.Property<string>("GivenName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("givenname");

                    b.Property<string>("HonorificPrefix")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("honorificprefix");

                    b.Property<string>("HonorificSuffix")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("honorificsuffix");

                    b.Property<string>("Locale")
                        .HasMaxLength(35)
                        .HasColumnType("varchar(35)")
                        .HasColumnName("locale");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("middlename");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(35)
                        .HasColumnType("varchar(35)")
                        .HasColumnName("preferredlanguage");

                    b.Property<string>("Timezone")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("timezone");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updatedatutc");

                    b.Property<string>("UserType")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("usertype");

                    b.HasKey("UserId");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("IX_scimuserprofiles_externalid");

                    b.ToTable("scimuserprofiles", (string)null);
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.SsfSetDelivery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("consumedat");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdatutc");

                    b.Property<string>("DeliveryKey")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("deliverykey")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("jti");

                    b.Property<string>("SetPayload")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("setpayload");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("streamid")
                        .UseCollation("utf8mb4_bin");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryKey")
                        .IsUnique()
                        .HasDatabaseName("AK_ssfsetdeliveries_deliverykey");

                    b.HasIndex("Jti")
                        .HasDatabaseName("IX_ssfsetdeliveries_jti");

                    b.HasIndex("StreamId", "ConsumedAt")
                        .HasDatabaseName("IX_ssfsetdeliveries_streamid_consumedat");

                    b.ToTable("ssfsetdeliveries", (string)null);
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.SsfStream", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("id");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("audience");

                    b.Property<string>("Authorization")
                        .HasColumnType("longtext")
                        .HasColumnName("authorization");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdatutc");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("deliverymethod");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("description");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("endpoint");

                    b.Property<string>("EventsRequested")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("eventsrequested");

                    b.Property<string>("OwnerClientId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ownerclientid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("streamid")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("SubjectScope")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("subjectscope");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updatedatutc");

                    b.Property<string>("VerificationChallengeHash")
                        .HasMaxLength(43)
                        .HasColumnType("varchar(43)")
                        .HasColumnName("verificationchallengehash")
                        .UseCollation("utf8mb4_bin");

                    b.Property<DateTime?>("VerificationExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("verificationexpiresatutc");

                    b.Property<string>("VerificationState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("verificationstate");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ssfstreams_status");

                    b.HasIndex("StreamId")
                        .IsUnique()
                        .HasDatabaseName("AK_ssfstreams_streamid");

                    b.HasIndex("OwnerClientId", "Status")
                        .HasDatabaseName("IX_ssfstreams_ownerclientid_status");

                    b.ToTable("ssfstreams", (string)null);
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.VaultKey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdatutc");

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("keyname");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("int")
                        .HasColumnName("keyversion");

                    b.Property<int>("LifecycleVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("lifecycleversion");

                    b.Property<string>("PublicJwk")
                        .HasColumnType("longtext")
                        .HasColumnName("publicjwk");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("purpose");

                    b.Property<DateTime?>("RetireAfterUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("retireafterutc");

                    b.Property<DateTime?>("RetiredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("retiredatutc");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revokedatutc");

                    b.Property<string>("SigningState")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("signingstate");

                    b.Property<byte[]>("WrappedKey")
                        .IsRequired()
                        .HasColumnType("longblob")
                        .HasColumnName("wrappedkey");

                    b.HasKey("Id");

                    b.HasIndex("KeyName", "KeyVersion")
                        .IsUnique()
                        .HasDatabaseName("AK_vaultkeys_keyname_keyversion");

                    b.ToTable("vaultkeys", (string)null);
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.VaultSecret", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AadJson")
                        .HasColumnType("longtext")
                        .HasColumnName("aadjson");

                    b.Property<string>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ciphertext");

                    b.Property<byte[]>("ContextId")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .HasColumnName("contextid");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiresatutc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("namespace");

                    b.Property<byte[]>("OwnerSubject")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .HasColumnName("ownersubject");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updatedatutc");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("updatedby");

                    b.HasKey("Id");

                    b.HasIndex("Type", "ContextId", "Name")
                        .IsUnique()
                        .HasDatabaseName("AK_vaultsecrets_context_name");

                    b.HasIndex("Type", "ContextId", "Namespace")
                        .HasDatabaseName("IX_vaultsecrets_context_namespace");

                    b.ToTable("vaultsecrets", (string)null);
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.VaultSigningKeyLifecycleOperation", b =>
                {
                    b.Property<string>("OperationId")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("operationid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("action");

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("keyname");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("int")
                        .HasColumnName("keyversion");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("occurredatutc");

                    b.Property<int?>("PreviousKeyVersion")
                        .HasColumnType("int")
                        .HasColumnName("previouskeyversion");

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("RetireAfterUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("retireafterutc");

                    b.HasKey("OperationId");

                    b.HasIndex("KeyName", "OccurredAtUtc")
                        .HasDatabaseName("IX_vaultsigningkeyoperations_keyname_occurred");

                    b.ToTable("vaultsigningkeyoperations", (string)null);
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.VaultSigningKeyLock", b =>
                {
                    b.Property<string>("KeyName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("keyname");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiresatutc");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("ownerid");

                    b.HasKey("KeyName");

                    b.ToTable("vaultsigningkeylocks", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Sufficit.Identity.Core.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Sufficit.Identity.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Sufficit.Identity.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId")
                                .HasColumnType("varbinary(1024)");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired()
                                .HasColumnType("longblob")
                                .HasColumnName("attestationobject");

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired()
                                .HasColumnType("longblob")
                                .HasColumnName("clientdatajson");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("createdat");

                            b1.Property<bool>("IsBackedUp")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("isbackedup");

                            b1.Property<bool>("IsBackupEligible")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("isbackupeligible");

                            b1.Property<bool>("IsUserVerified")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("isuserverified");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext")
                                .HasColumnName("name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired()
                                .HasColumnType("longblob")
                                .HasColumnName("publickey");

                            b1.Property<uint>("SignCount")
                                .HasColumnType("int unsigned")
                                .HasColumnName("signcount");

                            b1.Property<string>("Transports")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("userpasskeys");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Sufficit.Identity.Core.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sufficit.Identity.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Sufficit.Identity.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.ScimGroupGroupMember", b =>
                {
                    b.HasOne("Sufficit.Identity.Core.Entities.ScimGroup", "Group")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sufficit.Identity.Core.Entities.ScimGroup", "MemberGroup")
                        .WithMany()
                        .HasForeignKey("MemberGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("MemberGroup");
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.ScimGroupUserMember", b =>
                {
                    b.HasOne("Sufficit.Identity.Core.Entities.ScimGroup", "Group")
                        .WithMany("UserMembers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sufficit.Identity.Core.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.ScimUserProfile", b =>
                {
                    b.HasOne("Sufficit.Identity.Core.Entities.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("Sufficit.Identity.Core.Entities.ScimUserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("Sufficit.Identity.Core.Entities.ScimGroup", b =>
                {
                    b.Navigation("GroupMembers");

                    b.Navigation("UserMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
